name: social_media
description: "social media app with supabase"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.5.1
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  # Contains code to deal with internationalized/localized messages.
  intl: ^0.19.0
  # Simple direct Service Locator.
  get_it: ^7.7.0
  # an implementation of the popular ReactiveX api for asynchronous programming
  rxdart: ^0.28.0
  # Explicitly reads environment variables into a dart file from a .env file.
  envied: ^0.5.4+1
  # A declarative router for Flutter.
  go_router: ^14.2.7
  # Flutter Widgets that make it easy to implement the BLoC.
  flutter_bloc: ^8.1.6
  # Flutter integration for Supabase.
  supabase_flutter: ^2.6.0
  # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.9.0
  # Annotations for the freezed code-generator. This package does nothing without freezed too.
  freezed_annotation: ^2.4.4
  # Flutter library to load and cache network images
  cached_network_image: ^3.4.1
  # Converts already built widgets into skeleton loaders
  skeletonizer: ^1.4.2
  # An SVG rendering and widget library for Flutter.
  flutter_svg: ^2.0.10+1
  # Default icons asset for Cupertino widgets based on Apple styled icons.
  cupertino_icons: ^1.0.8
  # A library designed for seamless internet connectivity checks.
  internet_connection_checker: ^2.0.0
dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.12
  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.5.7
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.8.0
  # A builder that supports generated strongly-typed route helpers for package:go_router.
  go_router_builder: ^2.7.1
  # Generator for the Envied package.
  envied_generator: ^0.5.4+1
  # Customize Flutter's default native splash screen
  flutter_native_splash: ^2.4.1
  # A package which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.13.1
  # flutter lints contains a set of recommended lints to encourage good coding practices.
  flutter_lints: ^4.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
   - family: beVietnamPro
     fonts:
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-Thin.ttf
         weight: 100
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-ThinItalic.ttf
         style: italic
         weight: 100
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-ExtraLight.ttf
         weight: 200
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-ExtraLightItalic.ttf
         style: italic
         weight: 200
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-Light.ttf
         weight: 300
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-LightItalic.ttf
         style: italic
         weight: 300
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-Regular.ttf
         weight: 400
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-Italic.ttf
         style: italic
         weight: 400
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-Medium.ttf
         weight: 500
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-MediumItalic.ttf
         style: italic
         weight: 500
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-SemiBoldItalic.ttf
         style: italic
         weight: 600
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-Bold.ttf
         weight: 700
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-BoldItalic.ttf
         style: italic
         weight: 700
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-ExtraBold.ttf
         weight: 800
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-ExtraBoldItalic.ttf
         style: italic
         weight: 800
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-Black.ttf
         weight: 900
       - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-BlackItalic.ttf
         style: italic
         weight: 900


flutter_gen:
  output: lib/core/utils/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      class_name: AppAssets
      package_parameter_enabled: false
      directory_path_enabled: true
    exclude: []
  fonts:
    enabled: false
  colors:
    enabled: false