name: social_media
description: "social media app with supabase"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.5.1
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  # Contains code to deal with internationalized/localized messages.
  intl: ^0.19.0
  # Simple direct Service Locator.
  get_it: ^7.7.0
  # an implementation of the popular ReactiveX api for asynchronous programming
  rxdart: ^0.28.0
  # Explicitly reads environment variables into a dart file from a .env file.
  envied: ^0.5.4+1
  # A declarative router for Flutter.
  go_router: ^14.2.7
  # Flutter Widgets that make it easy to implement the BLoC.
  flutter_bloc: ^8.1.6
  # Flutter integration for Supabase.
  supabase_flutter: ^2.6.0
  # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.9.0
  # Annotations for the freezed code-generator. This package does nothing without freezed too.
  freezed_annotation: ^2.4.4
  # Flutter library to load and cache network images
  cached_network_image: ^3.4.1
  # Converts already built widgets into skeleton loaders
  skeletonizer: ^1.4.2
  # Default icons asset for Cupertino widgets based on Apple styled icons.
  cupertino_icons: ^1.0.8
dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.12
  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.5.7
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.8.0
  # A builder that supports generated strongly-typed route helpers for package:go_router.
  go_router_builder: ^2.7.1
  # Generator for the Envied package.
  envied_generator: ^0.5.4+1
  # Customize Flutter's default native splash screen
  flutter_native_splash: ^2.4.1
  # A package which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.13.1
  # flutter lints contains a set of recommended lints to encourage good coding practices.
  flutter_lints: ^4.0.0
flutter:
  generate: true
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700